const mapa = {
    'um': 1,
    'uma': 1,
    'dois': 2,
    'duas': 2,
    'três': 3,
    'tres': 3,
    'quatro': 4,
    'cinco': 5,
    'seis': 6,
    'sete': 7,
    'oito': 8,
    'nove': 9,
    'dez': 10,
    'onze': 11,
    'doze': 12,
    'treze': 13,
    'quatorze': 14,
    'catorze': 14,
    'quinze': 15,
    'dezesseis': 16,
    'dezessete': 17,
    'dezoito': 18,
    'dezenove': 19,
    'vinte': 20,
    'vinte e um': 21,
    'vinte e dois': 22,
    'vinte e três': 23,
    'vinte e quatro': 24,
    'vinte e cinco': 25,
    'vinte e seis': 26,
    'vinte e sete': 27,
    'vinte e oito': 28,
    'vinte e nove': 29,
    'trinta': 30,
    'trinta e um': 31,
    'trinta e dois': 32,
    'trinta e três': 33,
    'trinta e quatro': 34,
    'trinta e cinco': 35,
    'trinta e seis': 36,
    'trinta e sete': 37,
    'trinta e oito': 38,
    'trinta e nove': 39,
    'quarenta': 40,
    'quarenta e um': 41,
    'quarenta e dois': 42,
    'quarenta e três': 43,
    'quarenta e quatro': 44,
    'quarenta e cinco': 45,
    'quarenta e seis': 46,
    'quarenta e sete': 47,
    'quarenta e oito': 48,
    'quarenta e nove': 49,
    'cinquenta': 50
  };  

  
  module.exports = {
    mapa,
  }